### ISSUE TITLE
Use upstream `osmosis-rust` instead of our own fork

### ISSUE THREAD

**Issue by apollo-pacman** [apollodao/cw-dex#51]
currently we are using our own fork of `osmosis-rust`. When all PRs have been merged to `main` in upstream we should use a commit from upstream `main`

#### Pending PR:s
- [ ] https://github.com/osmosis-labs/osmosis-rust/pull/49 (was merged to `osmosis-main-clone` instead of `main`)

**Comment by georgemc98** [comment]
@apollo-pacman 

https://github.com/apollodao/cw-dex/commit/6ba4282f310edd2290e6d5555b78bfc6d7645635

I updated to the specific commit on `osmosis-main-clone`

**Comment by apollo-pacman** [comment]
Fixed by https://github.com/apollodao/cw-dex/commit/6ba4282f310edd2290e6d5555b78bfc6d7645635
